var searchData=
[
  ['tcpclient',['TCPClient',['../class_client_1_1_t_c_p_client.html',1,'Client::TCPClient'],['../class_client_1_1_t_c_p_client.html#ad3411e7d9e5bc52fb64961b89bf0fd74',1,'Client::TCPClient::TCPClient()']]],
  ['tcpclient_2ecpp',['TCPClient.cpp',['../_t_c_p_client_8cpp.html',1,'']]],
  ['tcpclient_2eh',['TCPClient.h',['../_t_c_p_client_8h.html',1,'']]],
  ['tcpserver',['TCPServer',['../class_server_1_1_t_c_p_server.html',1,'Server::TCPServer'],['../class_server_1_1_t_c_p_server.html#a3a5e3cfe42c676ed71f2bc58dcc92bda',1,'Server::TCPServer::TCPServer()']]],
  ['tcpserver_2ecpp',['TCPServer.cpp',['../_t_c_p_server_8cpp.html',1,'']]],
  ['tcpserver_2eh',['TCPServer.h',['../_t_c_p_server_8h.html',1,'']]],
  ['teardown',['TearDown',['../classanonymous__namespace_02_test_communication_8h_03_1_1_test_communication.html#a4dfcc3f0dd6e9228e459444d06b2f3eb',1,'anonymous_namespace{TestCommunication.h}::TestCommunication::TearDown()'],['../classanonymous__namespace_02_test_messages_handler_8h_03_1_1_test_messages_handler.html#ad617df89eb461a220fd29168e6ddb8b5',1,'anonymous_namespace{TestMessagesHandler.h}::TestMessagesHandler::TearDown()']]],
  ['test_5ff',['TEST_F',['../namespaceanonymous__namespace_02_test_communication_8h_03.html#a70e71d112c09d8bd8a6aaee07de752a4',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, StartServerDontThrowExceptions)'],['../namespaceanonymous__namespace_02_test_communication_8h_03.html#af2aadaf9497179c69bef4edae8870ef8',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, ClientThrowsIfServerOffline)'],['../namespaceanonymous__namespace_02_test_communication_8h_03.html#afee0709dc04e15f7c551f67d6cef3107',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, ServerClosesOnDestructor)'],['../namespaceanonymous__namespace_02_test_communication_8h_03.html#af882f53d15fcc6d28b7edac0ccd9cf41',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, CommunicationWithMultipleClients)'],['../namespaceanonymous__namespace_02_test_communication_8h_03.html#a7412e760b105abac94a0bddba689f73a',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, AuthenticateThrowsWithWrongPsw)'],['../namespaceanonymous__namespace_02_test_communication_8h_03.html#a37c44b3fccc088c984c3bdc2b83a43d0',1,'anonymous_namespace{TestCommunication.h}::TEST_F(TestCommunication, CannotChangeOrReadDBIfNotAuthenticated)'],['../namespaceanonymous__namespace_02_test_messages_handler_8h_03.html#a48db58847083f30364d3006e3c38cf1b',1,'anonymous_namespace{TestMessagesHandler.h}::TEST_F(TestMessagesHandler, ThrowOnInvalidInput)'],['../namespaceanonymous__namespace_02_test_messages_handler_8h_03.html#a5896a5b89f2bd449c64c29c22521849b',1,'anonymous_namespace{TestMessagesHandler.h}::TEST_F(TestMessagesHandler, AuthenticateMessageProcessedCorrectly)'],['../namespaceanonymous__namespace_02_test_messages_handler_8h_03.html#af167475ed9531817f3dcb1ede8319433',1,'anonymous_namespace{TestMessagesHandler.h}::TEST_F(TestMessagesHandler, StoreMessageProcessedCorrectly)']]],
  ['testcommunication',['TestCommunication',['../classanonymous__namespace_02_test_communication_8h_03_1_1_test_communication.html',1,'anonymous_namespace{TestCommunication.h}']]],
  ['testcommunication_2eh',['TestCommunication.h',['../_test_communication_8h.html',1,'']]],
  ['testmessageshandler',['TestMessagesHandler',['../classanonymous__namespace_02_test_messages_handler_8h_03_1_1_test_messages_handler.html',1,'anonymous_namespace{TestMessagesHandler.h}']]],
  ['testmessageshandler_2eh',['TestMessagesHandler.h',['../_test_messages_handler_8h.html',1,'']]],
  ['threads',['threads',['../class_server_1_1_t_c_p_server.html#abc0b23edcd67c6dbac8c28b3cbcc6ad6',1,'Server::TCPServer']]]
];
