TestApp: Client::TCPClient Class Reference
Client::TCPClient Class Reference
#include <TCPClient.h>
Public Member Functions
TCPClient (std::string aAddress, int aPort)
Creates TCP client.
~TCPClient ()
Closes TCP client.
void Create (std::string &&aId, std::string &&aName, std::string &&aPsw)
Creates credentials data.
void Delete (std::string &&aId, std::string &&aName)
Deletes credentials data.
void Authenticate (std::string aPsw)
std::string Read ()
Private Member Functions
void Close ()
Closes TCP socket.
void Send (gpb::Message &aMessage)
Sends message to server.
Private Attributes
int sockedFd
Socket descriptor.
struct sockaddr_in server
Structure describing an Internet socket address.
bool isAuthenticated
Detailed Description
Class that connects to tcp socket and send request to create, read, update or delete credentials data
Definition at line 23 of file TCPClient.h.
Constructor & Destructor Documentation
TCPClient()
TCPClient::TCPClient (std::string aAddress, int aPort)
Creates TCP client.
Parameters
aAddress Server address
aPort Server port
Exceptions
Common::SocketException Cound not create socket or connect to server
Definition at line 7 of file TCPClient.cpp.
References SELECT_TIMEOUT, server, and sockedFd.
     : sockedFd(-1)
     , isAuthenticated(false)
 {
     if(sockedFd == -1) {
         sockedFd = socket(AF_INET, SOCK_STREAM , 0);
         if (sockedFd == -1) {
             throw Common::SocketException("Could not create socket");
         }
     }
     server.sin_addr.s_addr = inet_addr(aAddress.c_str());
     server.sin_family = AF_INET;
     server.sin_port = htons( aPort );
     if (connect(sockedFd , reinterpret_cast<struct sockaddr *>(&server) , sizeof(server)) < 0) {
         throw Common::SocketException("Connect failed.");
     }
     setsockopt(sockedFd, SOL_SOCKET, SO_RCVTIMEO, (const char*)&SELECT_TIMEOUT, sizeof(SELECT_TIMEOUT));
 }
~TCPClient()
TCPClient::~TCPClient ()
Closes TCP client.
Definition at line 27 of file TCPClient.cpp.
References Close().
 {
     Close();
 }
Member Function Documentation
Authenticate()
void TCPClient::Authenticate (std::string aPsw)
Definition at line 95 of file TCPClient.cpp.
References DEBUG_LOG, isAuthenticated, Read(), and Send().
Referenced by anonymous_namespace{TestCommunication.h}::TEST_F().
{
     gpb::Message message;
     DEBUG_LOG(aPsw);
     message.set_action(gpb::Message_Action::Message_Action_AUTHENTICATE);
     auto* record = message.mutable_record();
     record->set_password(aPsw);
     Send(message);
     std::string response = Read();
     DEBUG_LOG(response);
     // TODO: need to create gpb response message, not only for this
     isAuthenticated = response.compare(std::string("come on in" + 0)) == 0;
     if (!isAuthenticated) throw Common::AuthenticationFailedException();
 }
Close()
void TCPClient::Close () private
Closes TCP socket.
Definition at line 109 of file TCPClient.cpp.
References sockedFd.
Referenced by ~TCPClient().
 {
     close( sockedFd );
 }
Create()
void TCPClient::Create (std::string && aId, std::string && aName, std::string && aPsw)
Creates credentials data.
Parameters
aId Credential id
aName Username
aPsw Password
Exceptions
Common::SocketException Socket is not opened
Common::CommunicationError Error happened during send operation
Definition at line 44 of file TCPClient.cpp.
References isAuthenticated, and Send().
Referenced by anonymous_namespace{TestCommunication.h}::TEST_F().
 {
     if (!isAuthenticated) throw Common::AuthenticationFailedException();
     gpb::Message message;
     message.set_action(gpb::Message_Action::Message_Action_CREATE);
     auto* record = message.mutable_record();
     record->set_id(aId);
     record->set_username(aName);
     record->set_password(aPsw);
     Send(message);
 }
Delete()
void TCPClient::Delete (std::string && aId, std::string && aName)
Deletes credentials data.
Parameters
aId Credential id
aName Username
Exceptions
Common::SocketException Socket is not opened
Common::CommunicationError Error happened during send operation
Definition at line 57 of file TCPClient.cpp.
References isAuthenticated, and Send().
Referenced by anonymous_namespace{TestCommunication.h}::TEST_F().
 {
     if (!isAuthenticated) throw Common::AuthenticationFailedException();
     gpb::Message message;
     message.set_action(gpb::Message_Action::Message_Action_DELETE);
     auto* record = message.mutable_record();
     record->set_id(aId);
     record->set_username(aName);
     Send(message);
 }
Read()
std::string TCPClient::Read ()
Definition at line 78 of file TCPClient.cpp.
References sockedFd.
Referenced by Authenticate().
 {
     char buffer[1] = {'?'};
     std::stringstream reply;
     while (buffer[0] != 0) {
         if( recv(sockedFd , buffer , sizeof(buffer) , 0) < 0)
         {
             throw Common::SocketException("Receive failed!");
         }
         reply << buffer[0];
     }
     std::string str(reply.str());
     str.erase(str.length() - 1);
     return std::move(str);
 }
Send()
void TCPClient::Send (gpb::Message & aMessage) private
Sends message to server.
Parameters
aMessage Reference to message
Exceptions
Common::SocketException Socket is not opened
Common::CommunicationError Error happened during send operation
Definition at line 32 of file TCPClient.cpp.
References sockedFd.
Referenced by Authenticate(), Create(), and Delete().
 {
     if(sockedFd == -1) {
         throw Common::SocketException("Connect failed.");
     }
     std::string msgToSend(aMessage.SerializeAsString() + '\0');
     if(send(sockedFd, msgToSend.c_str(), msgToSend.length(), 0) < 0) {
         throw Common::CommunicationError("Send failed");
     }
 }
Field Documentation
isAuthenticated
bool Client::TCPClient::isAuthenticated private
Definition at line 99 of file TCPClient.h.
Referenced by Authenticate(), Create(), and Delete().
server
struct sockaddr_in Client::TCPClient::server private
Structure describing an Internet socket address.
Definition at line 97 of file TCPClient.h.
Referenced by TCPClient().
sockedFd
int Client::TCPClient::sockedFd private
Socket descriptor.
Definition at line 92 of file TCPClient.h.
Referenced by Close(), Read(), Send(), and TCPClient().
The documentation for this class was generated from the following files:
client/src/TCPClient.h
client/src/TCPClient.cpp