TestApp: Server::MessagesHandler Class Reference
Server::MessagesHandler Class Reference
#include <MessagesHandler.h>
Public Member Functions
MessagesHandler ()
MessagesHandler c-tor.
MessagesHandler (std::shared_ptr< dataStorageHandler > aStorageHandler)
MessagesHandler c-tor.
~MessagesHandler ()=default
MessagesHandler c-tor.
std::string ProcessMessage (socket_description &user, std::string &aMsg)
Private Attributes
std::shared_ptr< dataStorageHandler > storageHandler
Detailed Description
Definition at line 16 of file MessagesHandler.h.
Constructor & Destructor Documentation
MessagesHandler() [1/2]
Server::MessagesHandler::MessagesHandler () inline
MessagesHandler c-tor.
Definition at line 22 of file MessagesHandler.h.
References storageHandler.
         {
             storageHandler = std::make_shared<dataStorageHandler>();
         };
MessagesHandler() [2/2]
Server::MessagesHandler::MessagesHandler (std::shared_ptr< dataStorageHandler > aStorageHandler) inline
MessagesHandler c-tor.
Parameters
aStorageHandler pointer to storage handler
Note
Used only with mocks
Definition at line 32 of file MessagesHandler.h.
References storageHandler, and ~MessagesHandler().
         {
             storageHandler = aStorageHandler;
         };
~MessagesHandler()
Server::MessagesHandler::~MessagesHandler () default
MessagesHandler c-tor.
Referenced by MessagesHandler().
Member Function Documentation
ProcessMessage()
std::string Server::MessagesHandler::ProcessMessage (socket_description & user, std::string & aMsg) inline
Definition at line 42 of file MessagesHandler.h.
References Server::socket_description::isAuthenticated, and storageHandler.
Referenced by Server::TCPServer::listenLoop(), and anonymous_namespace{TestMessagesHandler.h}::TEST_F().
         {
             gpb::Message parsedMsg;
             if(!parsedMsg.ParseFromString(aMsg)) {
                 throw Common::MessageParseException();
             }
             if ((!user.isAuthenticated) && (parsedMsg.action() != gpb::Message_Action::Message_Action_AUTHENTICATE)) {
                 throw Common::AuthenticationFailedException();
             }
             switch (parsedMsg.action())
             {
                 case gpb::Message_Action::Message_Action_CREATE: {
                     storageHandler->Store(parsedMsg.record());
                     return std::string("created"); // TODO: think about various status responses type from server to client
                 }
                 case gpb::Message_Action::Message_Action_READ: {
                     return storageHandler->Read(parsedMsg.record());
                 }
                 case gpb::Message_Action::Message_Action_UPDATE: {
                     storageHandler->Update(parsedMsg.record());
                     return std::string("update"); // TODO: think about various status responses type from server to client
                 }
                 case gpb::Message_Action::Message_Action_DELETE: {
                     storageHandler->Remove(parsedMsg.record());
                     return std::string("deleted"); // TODO: think about various status responses type from server to client
                 }
                 case gpb::Message_Action::Message_Action_AUTHENTICATE: {
                     user.isAuthenticated = storageHandler->Authenticate(parsedMsg.record());
                     return user.isAuthenticated ? std::string("come on in") : std::string("You not shall pass"); // TODO: think about various status responses type from server to client
                 }
                 default:
                     break;
             }
             return std::string("unknown command");
         }
Field Documentation
storageHandler
std::shared_ptr<dataStorageHandler> Server::MessagesHandler::storageHandler private
Definition at line 81 of file MessagesHandler.h.
Referenced by MessagesHandler(), and ProcessMessage().
The documentation for this class was generated from the following file:
server/src/MessagesHandler.h