TestApp: server/main_server.cpp File Reference
main_server.cpp File Reference
#include <iostream>
#include <csignal>
#include <ctime>
#include <thread>
#include <fstream>
#include "TCPServer.h"
#include "Exceptions.h"
#include "socket_description.h"
#include "MessagesHandler.h"
Functions
constexpr int SERVER_PORT (5050)
void close_app (int s)
void writeToLog (std::string &msgToLog)
int main (int, char **)
Variables
const std::vector< int > SOCKET_OPTIONS { SO_REUSEPORT, SO_REUSEADDR }
bool running = true
Function Documentation
close_app()
void close_app (int s)
Definition at line 20 of file main_server.cpp.
References running.
Referenced by main().
                       {
     running = false;
 }
main()
int main (int , char **)
Definition at line 31 of file main_server.cpp.
References Server::TCPServer::AcceptNewClients(), close_app(), running, and Common::SocketException::what().
 {
     std::signal(SIGINT, close_app);
     std::signal(SIGKILL, close_app);
     try
     {
         TCPServer tcp;
         tcp.AcceptNewClients();
         while (running)
         {
             /* code */
         }
     }
     catch(const Common::SocketException& e)
     {
         std::cout << e.what() << '\n';
     }
     std::cout << "Closing" << std::endl;
     return 0;
 }
SERVER_PORT()
constexpr int SERVER_PORT (5050)
writeToLog()
void writeToLog (std::string & msgToLog)
Definition at line 24 of file main_server.cpp.
 {
   std::ofstream outfile;
   outfile.open("test.txt", std::ios_base::app);
   outfile << msgToLog << std::endl;
 }
Variable Documentation
running
bool running = true
Definition at line 19 of file main_server.cpp.
Referenced by close_app(), and main().
SOCKET_OPTIONS
const std::vector<int> SOCKET_OPTIONS { SO_REUSEPORT, SO_REUSEADDR }
Definition at line 17 of file main_server.cpp.