TestApp: anonymous_namespace{TestCommunication.h} Namespace Reference
anonymous_namespace{TestCommunication.h} Namespace Reference
Data Structures
class TestCommunication
Functions
TEST_F (TestCommunication, StartServerDontThrowExceptions)
TEST_F (TestCommunication, ClientThrowsIfServerOffline)
TEST_F (TestCommunication, ServerClosesOnDestructor)
TEST_F (TestCommunication, CommunicationWithMultipleClients)
TEST_F (TestCommunication, AuthenticateThrowsWithWrongPsw)
TEST_F (TestCommunication, CannotChangeOrReadDBIfNotAuthenticated)
Function Documentation
TEST_F() [1/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , StartServerDontThrowExceptions)
Definition at line 34 of file TestCommunication.h.
{
         ASSERT_NO_THROW(Server::TCPServer ().AcceptNewClients());
     }
TEST_F() [2/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , ClientThrowsIfServerOffline)
Definition at line 38 of file TestCommunication.h.
References DEFAULT_IP, and DEFAULT_PORT.
{
         ASSERT_THROW(Client::TCPClient (DEFAULT_IP, DEFAULT_PORT), Common::SocketException);
     }
TEST_F() [3/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , ServerClosesOnDestructor)
Definition at line 42 of file TestCommunication.h.
References DEFAULT_IP, DEFAULT_PORT, and MASTER_PASSWORD.
{
         {
             Server::TCPServer server {};
             ASSERT_TRUE(server.is_online());
             ASSERT_NO_THROW(server.AcceptNewClients());
             Client::TCPClient client(DEFAULT_IP, DEFAULT_PORT);
             client.Authenticate(MASTER_PASSWORD);
             client.Create("id_client", "client", "passclient");
         }   // Destroys server object when leaves this scope
         // expect to throw, because server is offline
         ASSERT_THROW(Client::TCPClient (DEFAULT_IP, DEFAULT_PORT), Common::SocketException);
     }
TEST_F() [4/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , CommunicationWithMultipleClients)
Definition at line 56 of file TestCommunication.h.
References Server::TCPServer::AcceptNewClients(), Client::TCPClient::Authenticate(), Client::TCPClient::Create(), DEFAULT_IP, DEFAULT_PORT, and MASTER_PASSWORD.
{
         ASSERT_EQ(getDbFileSize(), -1); // -1 since there is no file
         for (size_t i = 0; i < 10; i++)
         {
             Server::TCPServer server {};
             server.AcceptNewClients();
             Client::TCPClient client(DEFAULT_IP, DEFAULT_PORT);
             Client::TCPClient client2(DEFAULT_IP, DEFAULT_PORT);
             client.Authenticate(MASTER_PASSWORD);
             client2.Authenticate(MASTER_PASSWORD);
             client.Create("id_client" + i, "client", "passclient");
             client2.Create("id_client2" + i, "client2", "passclient2");
         }
         ASSERT_GT(getDbFileSize(), 0); // db file not empty
     }
TEST_F() [5/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , AuthenticateThrowsWithWrongPsw)
Definition at line 74 of file TestCommunication.h.
References Server::TCPServer::AcceptNewClients(), Client::TCPClient::Authenticate(), DEFAULT_IP, and DEFAULT_PORT.
{
         Server::TCPServer server {};
         server.AcceptNewClients();
         Client::TCPClient client(DEFAULT_IP, DEFAULT_PORT);
         ASSERT_THROW(client.Authenticate("12345678"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Authenticate("UNKNOWN"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Authenticate("password"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Authenticate("admin"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Authenticate("root"), Common::AuthenticationFailedException);
     }
TEST_F() [6/6]
anonymous_namespace{TestCommunication.h}::TEST_F (TestCommunication , CannotChangeOrReadDBIfNotAuthenticated)
Definition at line 85 of file TestCommunication.h.
References Server::TCPServer::AcceptNewClients(), Client::TCPClient::Authenticate(), Client::TCPClient::Create(), DEFAULT_IP, DEFAULT_PORT, and Client::TCPClient::Delete().
{
         Server::TCPServer server {};
         server.AcceptNewClients();
         Client::TCPClient client(DEFAULT_IP, DEFAULT_PORT);
         ASSERT_THROW(client.Authenticate("12345678"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Create("id", "name", "pass"), Common::AuthenticationFailedException);
         // TODO: FIXME
         // ASSERT_THROW(client.Read(), Common::AuthenticationFailedException);
         // ASSERT_THROW(client.Update("id", "name", "pass"), Common::AuthenticationFailedException);
         ASSERT_THROW(client.Delete("id", "name"), Common::AuthenticationFailedException);
     }