TestApp: anonymous_namespace{TestMessagesHandler.h} Namespace Reference
anonymous_namespace{TestMessagesHandler.h} Namespace Reference
Data Structures
class TestMessagesHandler
Functions
TEST_F (TestMessagesHandler, ThrowOnInvalidInput)
TEST_F (TestMessagesHandler, AuthenticateMessageProcessedCorrectly)
TEST_F (TestMessagesHandler, StoreMessageProcessedCorrectly)
Function Documentation
TEST_F() [1/3]
anonymous_namespace{TestMessagesHandler.h}::TEST_F (TestMessagesHandler , ThrowOnInvalidInput)
Definition at line 47 of file TestMessagesHandler.h.
References Server::MessagesHandler::ProcessMessage().
{
         std::shared_ptr<MockdataStorageHandler> mockStorage = std::shared_ptr<MockdataStorageHandler>();
         EXPECT_CALL(*mockStorage, Store(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Read(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Update(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Remove(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Authenticate(_))
             .Times(0);
         Server::MessagesHandler messageHandler(mockStorage);
         Server::socket_description socket = getSocket();
         std::string msg{"INVALID MESSAGE!"};
         ASSERT_THROW(messageHandler.ProcessMessage(socket, msg), Common::MessageParseException);
     }
TEST_F() [2/3]
anonymous_namespace{TestMessagesHandler.h}::TEST_F (TestMessagesHandler , AuthenticateMessageProcessedCorrectly)
Definition at line 66 of file TestMessagesHandler.h.
References Server::MessagesHandler::ProcessMessage().
{
         std::shared_ptr<MockdataStorageHandler> mockStorage = std::shared_ptr<MockdataStorageHandler>();
         EXPECT_CALL(*mockStorage, Store(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Read(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Update(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Remove(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Authenticate(_))
             .Times(1).WillOnce(Return(true));
         Server::MessagesHandler messageHandler(std::move(mockStorage));
         Server::socket_description socket = getSocket();
         gpb::Message message;
         message.set_action(gpb::Message_Action_AUTHENTICATE);
         auto* record = message.mutable_record();
         record->set_password("MASTER_PASSWORD");
         std::string msg { message.SerializeAsString() };
         messageHandler.ProcessMessage(socket, msg);
     }
TEST_F() [3/3]
anonymous_namespace{TestMessagesHandler.h}::TEST_F (TestMessagesHandler , StoreMessageProcessedCorrectly)
Definition at line 92 of file TestMessagesHandler.h.
References Server::MessagesHandler::ProcessMessage().
{
         std::shared_ptr<MockdataStorageHandler> mockStorage = std::shared_ptr<MockdataStorageHandler>();
         EXPECT_CALL(*mockStorage, Store(_))
             .Times(1);
         EXPECT_CALL(*mockStorage, Read(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Update(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Remove(_))
             .Times(0);
         EXPECT_CALL(*mockStorage, Authenticate(_))
             .Times(0);
         Server::MessagesHandler messageHandler(std::move(mockStorage));
         Server::socket_description socket = getSocket();
         gpb::Message message = getMessage(gpb::Message_Action_CREATE);
         std::string msg { message.SerializeAsString() };
         messageHandler.ProcessMessage(socket, msg);
     }